language: java
jdk:
  - openjdk14
install:
  - wget http://archive.apache.org/dist/ant/binaries/apache-ant-1.10.7-bin.tar.gz
  - tar xvfvz apache-ant-1.10.7-bin.tar.gz
  - export PATH=`pwd`/apache-ant-1.10.7/bin:$PATH
services:
  - mysql
script: 'ant all'
sudo: required
before_script:
  - bash .travis.install-mysql-5.7.sh
  - mysql -u root -e 'CREATE DATABASE LAS2PEERMON;'
  - mysql -u root LAS2PEERMON < SBF.sql
after_success:
  - bash <(curl -s https://codecov.io/bash)