version: '3'

services:
  social-bot-manager:
    build: .
    environment:
      DATABASE_NAME: ${DATABASE_NAME:-SBF}
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT:-3306}
      DATABASE_USER: ${DATABASE_USER:-root}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-root}
    ports:
      - "8090:8080"
      - "9011:9011"
    depends_on:
      - db
  
  db:
    image: mysql:8
    platform: ${TARGETPLATFORM:-linux/amd64}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-root}
      MYSQL_DATABASE: ${DATABASE_NAME:-SBF}
      MYSQL_INITDB_SQL: /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./SBF.sql:/docker-entrypoint-initdb.d/init.sql
  